info:
  component: {projectName}
  
server:  
  port: 8080

spring:
  application:
    name: {projectName}
  jersey:
    type: filter
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: password
    driverClassName: com.mysql.jdbc.Driver
    hikari:
      idleTimeout: 15000
      minimumIdle: 5
      maximumPoolSize: 10
      connectionTimeout: 20000
      poolName: artifactPoolName-pool
      connectionTestQuery: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    open-in-view: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.id.new_generator_mappings: false
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.hbm2ddl.auto: none
  jackson:
    serialization:
      indent-output: true

application-config:
  mode: local
  wiremock: true
  wiremockPort: 9998
  version: 1.0